# Generated by Django 3.0.5 on 2020-05-23 08:19

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Slug',
            field=autoslug.fields.AutoSlugField(),
        ),
    ]
