# Generated by Django 3.0.5 on 2020-05-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200524_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Slug',
            field=models.SlugField(default='article.details', max_length=200, unique=True),
        ),
    ]
