# Generated by Django 3.0.5 on 2020-06-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200524_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='MainTopic',
            field=models.CharField(default='Technology', max_length=100),
        ),
    ]
