# Generated by Django 3.0.5 on 2020-05-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200518_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(default='New Delhi'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='New Delhi', max_length=100),
        ),
    ]
